---
devices:
- hostname: R1
  device_type: access
  vendor: cisco
  clear_config: 'no'
  interfaces:
  - name: ethernet1
    ip_address: 10.0.0.1
    subnet_mask: 255.255.255.0
  ospf:
    process_id: '1'
    networks:
    - ip: 10.0.0.0
      wildcard: 0.0.0.255
      area: '0'
    redistribute:
      connected: false
      bgp: false
