---
devices:
  - hostname: R100
    device_type: access
    clear_config: no
    interfaces:
      - name: Et2/1
        ip_address: 10.0.0.1
        subnet_mask: "24"
    vlans:
      - id: "10"
        name: V10
    ospf:
      process_id: "1"
      networks:
        - ip: 10.0.0.0
          wildcard: 0.0.0.255
          area: "0"
      redistribute:
        connected: true
        bgp: true
